platform :ios, '12.1'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MM2021' do

  pod 'AFNetworking', '~> 3.0'
  pod 'FastEasyMapping', '~> 1.0.1'
  pod 'MBProgressHUD', '~> 0.9.2'
  pod 'ChameleonFramework'
  pod 'HPTextViewTapGestureRecognizer', '~> 0.1'
  pod 'DCAnimationKit'
  pod 'MPCoachMarks'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'SDWebImage', '~>3.8'
  pod 'NYTPhotoViewer', '~>1.1.0'

end
